### ISSUE TITLE
Server login issue

### ISSUE THREAD

**Issue by alphxn** [NetherGamesMC/PocketMine-MP#282]
### Issue description

- Expected result: What were you expecting to happen?
I was expecting to login into the server like normal.
- Actual result: What actually happened?
I got stuck in “Locating server” while it spammed the console.
### Steps to reproduce the issue

Fork the NG github, compile it, and add it to a server. Then try joining the server.

### OS and versions
* PocketMine-MP: 4.18.2
* PHP: PHP 8 (stable)
* Using JIT: no
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dries-c** [comment]
[PocketMine-MP.phar.zip](https://github.com/NetherGamesMC/PocketMine-MP/files/11140957/PocketMine-MP.phar.zip)
Could you try this phar?

**Comment by alphxn** [comment]
Nope same issue, just it doesn’t spam console, it doesn’t even show player logged in.

**Comment by W8wjn2ixis8** [comment]
Send me please PocketMine-MP.phar 🙏🙏🙏please

**Comment by alphxn** [comment]
[PocketMine-MP.phar.zip](https://github.com/NetherGamesMC/PocketMine-MP/files/11144776/PocketMine-MP.phar.zip)

just unzip it

**Comment by StefanFox-Dev** [comment]
Perhaps your host has IPv6, but your internet does not support. Try to put: enable-ipv6=off, or change MTU: 600.

**Comment by dries-c** [comment]
I've not been able to reproduce it sadly.
