### ISSUE TITLE
ItemStackRequestPacket error on versions 1.19.0-1.19.40

### ISSUE THREAD

**Issue by StefanFox-Dev** [NetherGamesMC/PocketMine-MP#283]
### Issue description

- Expected result: tried to craft, but crafting only sticks. NetworkSession player kicked: Bad packet: Erro
r processing ItemStackRequestPacket: Unexpected container UI ID 27
- Actual result: working craft

### Steps to reproduce the issue
1. Open workbench
2. ...

### OS and versions

* PocketMine-MP: 5.0.0-BETA-2
* PHP: 8.1
* Using JIT: no
* Server OS: Linux
* Game version: Android/iOS/Win10

### Plugins

no use plugins

### Crashdump, backtrace or other files

no crash

**Comment by alphxn** [comment]
how are you using pocketmine 5

Also if it on latest version send the pocketmine.phar here

**Comment by StefanFox-Dev** [comment]
Im not using phar.
https://github.com/NetherGamesMC/PocketMine-MP/tree/next-major

**Comment by dries-c** [comment]
Amazing, i'll take a look right now
