### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by alphxn** [NetherGamesMC/PocketMine-MP#285]
### Issue description

- Expected result: What were you expecting to happen?
I was expecting to login into the server like normal.
- Actual result: What actually happened?
I got stuck in “Locating server” while it spammed the console. The errors looked like chunk rendering issue.
### Steps to reproduce the issue

Fork the NG github, compile it, and add it to a server. Then try joining the server.

### OS and versions
* PocketMine-MP: 4.18.2
* PHP: PHP 8 (stable)
* Using JIT: no
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by alphxn** [comment]
i got the starting of the error
![Uploading B771465C-8383-4422-80E5-932993F69B6E.jpeg…]()

**Comment by dries-c** [comment]
The image doesn't seem to load for me

**Comment by alphxn** [comment]
![Uploading FF553742-AA98-4D02-82F9-5F6C6AD8288B.jpeg…]()

**Comment by alphxn** [comment]
hm idk wait can i open a discord ticket and send it there?

**Comment by dries-c** [comment]
Sure, whatever works for you

**Comment by alphxn** [comment]
[Uploading message.txt…]()

**Comment by alphxn** [comment]
[message.txt](https://github.com/NetherGamesMC/PocketMine-MP/files/11309436/message.txt)

**Comment by dries-c** [comment]
Write of 1691 bytes failed with errno=28 No space left on device  => means your disk or memory is full
