### ISSUE TITLE
Smithing Table does not work

### ISSUE THREAD

**Issue by StefanFox-Dev** [NetherGamesMC/PocketMine-MP#288]
### Issue description

- Expected result: Obtain a Netherite Sword
- Actual result: Got nothing

### Steps to reproduce the issue
1. Open Smithing Table
2. Place any diamond item and any amount of netherite
3. The problem has been observed since NG-ALPHA2, on the original PM there is no such problem.

### OS and versions
* PocketMine-MP: PocketMine-MP 5.0.0-BETA2
* PHP: 8.1
* Using JIT: yes
* Server OS: Linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
no use

### Crashdump, backtrace or other files
no crash

**Comment by dries-c** [comment]
Could you turn on debug and send me the outputN

**Comment by StefanFox-Dev** [comment]
Debug NetworkSession:  Syncing slots 0, 1, 7, 12, 13, 14, 16, 17, 19 in inventory pocketmine\inventory\PlayerInventory#58720

**Comment by StefanFox-Dev** [comment]
![Screenshot_20230423-123605_Termius](https://user-images.githubusercontent.com/59245729/233832490-5d78261c-e771-4440-9ca9-6dfff378bd8f.jpg)

**Comment by StefanFox-Dev** [comment]
![Screenshot_20230423-123500_Minecraft](https://user-images.githubusercontent.com/59245729/233832548-bab6dfd2-14b4-4ee3-880c-77106d9146b8.jpg)

**Comment by dries-c** [comment]
Could you test on the latest version if this issue still occurs?

**Comment by StefanFox-Dev** [comment]
Yes. But now there is no red cross, but still, it does not work

**Comment by StefanFox-Dev** [comment]
![Screenshot_20230430-090925_Minecraft](https://user-images.githubusercontent.com/59245729/235338672-0e149692-a6a1-491a-873f-8f0a3f928dce.jpg)

**Comment by StefanFox-Dev** [comment]
Still would ask, to remove support versions 1.18.10-1.18.32 with PM5. It will not be supported, due to the introduction of blocks from > 1.19.0

**Comment by StefanFox-Dev** [comment]
Error: Unmapped string ID "minecraft:mangrove_planks"
File: pmsrc/vendor/nethergamesmc/bedrock-protocol/src/serializer/ItemTypeDictionary
Line: 54
Type: InvalidArgumentException

**Comment by dries-c** [comment]
Well the plan is to put in a minimum version, and upgrade from there in the future. Instead of using the maximum version and downgrading. However this still isn't available.

**Comment by StefanFox-Dev** [comment]
This is off topic, of course, but branch major-next (85833e8) creative inventory broke, many blocks have AIR texture.

**Comment by dries-c** [comment]
Could you make a separate issue for this?

**Comment by dries-c** [comment]
Is this still a thing?

**Comment by StefanFox-Dev** [comment]
xd, 1.20 the interface has changed

**Comment by StefanFox-Dev** [comment]
![Screenshot_20230609-160742_Minecraft](https://github.com/NetherGamesMC/PocketMine-MP/assets/59245729/298cae98-3d8f-4a98-80c2-4b22c5107a9c)

**Comment by StefanFox-Dev** [comment]
fix not work

**Comment by StefanFox-Dev** [comment]
![Screenshot_20230624-230047_Minecraft](https://github.com/NetherGamesMC/PocketMine-MP/assets/59245729/524ed841-79cf-4461-ba78-0c9f75347069)
1.18-1.19

**Comment by dries-c** [comment]
But does it work with it the new version?

**Comment by StefanFox-Dev** [comment]
1.20? At 1.20, there is not even an original pmmp. added some coloring...

**Comment by dries-c** [comment]
well then it won't be supported for older versions either, since they don't appear to be BC

**Comment by StefanFox-Dev** [comment]
1.20 not work

**Comment by StefanFox-Dev** [comment]
oh
