### ISSUE TITLE
Server crashed Error: Player is not connected

### ISSUE THREAD

**Issue by MaskioSss** [NetherGamesMC/PocketMine-MP#290]
PocketMine-MP Crash Dump Thu Apr 13 13:19:24 UTC 2023

PocketMine-MP version: 4.19.1+dev [Protocol 575]
Git commit: 5265ac3475390c64b21b1372bc5c26243deefe48
PHP version: 8.0.28
OS: Linux, linux

Error: Player is not connected
File: pmsrc/src/player/Player
Line: 603
Type: LogicException
Backtrace:
#0 pmsrc/src/player/Player(2040): pocketmine\player\Player->getNetworkSession()
#1 pmsrc/src/Server(1294): pocketmine\player\Player->sendMessage(string[34] ..8[] ..fFolvzz: ..fdot todo skizo)
#2 pmsrc/src/player/Player(1499): pocketmine\Server->broadcastMessage(string[34] ..8[] ..fFolvzz: ..fdot todo skizo, array[7])
#3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(167): pocketmine\player\Player->chat(string[14] dot todo skizo)
#4 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/TextPacket(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleText(object pocketmine\network\mcpe\protocol\TextPacket#759499)
#5 pmsrc/src/network/mcpe/NetworkSession(507): pocketmine\network\mcpe\protocol\TextPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#706898)
#6 pmsrc/src/network/mcpe/NetworkSession(450): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\TextPacket#759499, string[43] ....Folvzz.dot todo skizo.2535431927109272.)
#7 pmsrc/src/network/mcpe/raklib/RakLibInterface(187): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[83] ..dd`s..)...K./Q(.O.W(.....0256516.4274..F........0../.........pCC......a.Wo....)
#8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 37, string[92] ..{.>RZ`@........!Q.z.......@.,...].V..5........f=..'..+Lrl.u}.3.Jl$....t.+h}z..)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#31949)
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#13 pmsrc/src/Server(1687): pocketmine\snooze\SleeperHandler->sleepUntil(float 1681391964.3193)
#14 pmsrc/src/Server(1073): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[16] /home/container/, string[24] /home/container/plugins/)
#16 pmsrc/src/PocketMine(362): pocketmine\server()
#17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[594] 		return $this->isConnected();
[595] 	}
[596] 
[597] 	public function isConnected() : bool{
[598] 		return $this->networkSession !== null && $this->networkSession->isConnected();
[599] 	}
[600] 
[601] 	public function getNetworkSession() : NetworkSession{
[602] 		if($this->networkSession === null){
[603] 			throw new \LogicException("Player is not connected");
[604] 		}
[605] 		return $this->networkSession;
[606] 	}
[607] 
[608] 	/**
[609] 	 * Gets the username
[610] 	 */
[611] 	public function getName() : string{
[612] 		return $this->username;
[613] 	}

Loaded plugins:
Anti2x1 0.0.3 by Phqzing for API(s) 4.0.0
AntiToolbox 1.0.0 by  for API(s) 4.0.0
BuilderTools 1.4.0-beta2 by CzechPMDevs, VixikHD for API(s) 4.0.0
ClanEvents 0.1 by Liphe for API(s) 4.0.0
CleanChat 0.0.1 by  for API(s) 4.7.4
CustomLevelKB 0.2.0 by SVega for API(s) 3.2.0, 4.0.0
CustomPVP 1.0.0 by HenryDM for API(s) 4.0.0
DEVirion 1.2.8 by poggit, SOFe for API(s) 4.0.0
DevTools 1.15.0 by PocketMine Team for API(s) 4.0.0
DeviceACM 2.0.0 by fernanACM for API(s) 4.0.0
FormAPI 2.1.0 by jojoe77777 for API(s) 4.0.0
LhScoreTag 0.1 by LightDemon for API(s) 4.0.0
MultiWorld 2.0.0-beta1 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 4.0.0
Netherite 2.3 by Wertzui123 for API(s) 4.0.0
NoVoid 1.0.0 by Electro for API(s) 4.0.0
PoryonCore 1 by PoryonInc for API(s) 4.0.0
Profile 0.1 by  for API(s) 3.0.0, 4.0.0
PureChat 2 by cu for API(s) 4.0.0
PurePerms 2.0.2 by Vecnavium , 64FF00 & ProjectInfinity for API(s) 4.0.0
Reports 2.0.0 by Didah (@Diduhless) for API(s) 4.0.0
Scoreboard 0.1 by Liphe for API(s) 4.0.0
SecurityGuards 1.0.0 by  for API(s) 4.0.0
Stuff 1.0.0 by AgÃªncia Zunion for API(s) 4.0.0
TPAll-PM4 1.3 by fernanACM, matymare for API(s) 4.0.0
WBprotect 1.0.0 by  for API(s) 4.0.0
WorldProtect 2.3.14 by aliuly for API(s) 4.0.0

uname -a: Linux cd0959e2-e18d-48c4-bf40-3b7ced19c5a7 5.4.0-1092-oracle #101~18.04.1-Ubuntu SMP Tue Jan 10 20:59:25 UTC 2023 aarch64
Zend version: 4.0.28
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.10.2@459f2781e1a08d52ee56b0b1444086e038561e3f
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.5.0@42060ed45344789fb9f21f9f1864fc47b9e3507b
- nethergamesmc/bedrock-data dev-master@3e6cdbe197aec1da83a93cbd079652768f582184
- nethergamesmc/bedrock-protocol dev-master@744f6b675a8cc0797e2fa83f6b4114c0f038f288
- netresearch/jsonmapper v4.2.0@f60565f8c0566a31acf06884cdaa591867ecc956
- pocketmine/bedrock-block-upgrade-schema 1.1.1@e0540343e649a92126a1d4071ec401a811416c76
- pocketmine/bedrock-item-upgrade-schema 1.1.0@aab89a1f121a0c127557a4a0cf981330301c9c45
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.3.1@a0421f1e9e0b0c619300fb92d593283378f6a5e1
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.19.5@71af5f9bd23b4e4bad8920dac7f4fe08e5205f7d
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
... (169 linhas)

**Comment by MaskioSss** [comment]
I just made a plugin to see if this is more accurate of an answer from you because I'm new to it. 
[FixPlayerConnect.zip](https://github.com/NetherGamesMC/PocketMine-MP/files/11222852/FixPlayerConnect.zip)

**Comment by MaskioSss** [comment]
[02:09:15.537] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: kllits3r
[02:09:15.538] [Server thread/CRITICAL]: LogicException: "Player is not connected" (EXCEPTION) in "pmsrc/src/player/Player" at line 603
--- Stack trace ---
  #0 pmsrc/src/player/Player(2040): pocketmine\player\Player->getNetworkSession()
  #1 pmsrc/src/Server(1294): pocketmine\player\Player->sendMessage(string[38] ..8[] ..fkllits3r: ..fkbbbbbbbbbbbbbbb)
  #2 pmsrc/src/player/Player(1499): pocketmine\Server->broadcastMessage(string[38] ..8[] ..fkllits3r: ..fkbbbbbbbbbbbbbbb, array[5])
  #3 pmsrc/src/network/mcpe/handler/InGamePacketHandler(167): pocketmine\player\Player->chat(string[16] kbbbbbbbbbbbbbbb)
  #4 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/TextPacket(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleText(object pocketmine\network\mcpe\protocol\TextPacket#730319)
  #5 pmsrc/src/network/mcpe/NetworkSession(507): pocketmine\network\mcpe\protocol\TextPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#684446)
  #6 pmsrc/src/network/mcpe/NetworkSession(450): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\TextPacket#730319, string[47] ....kllits3r.kbbbbbbbbbbbbbbb.2535464192891533.)
  #7 pmsrc/src/network/mcpe/raklib/RakLibInterface(187): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[116] .m.../....kllits3r.kbbbbbbbbbbbbbbb.2535464192891533.<....HA.\.@ ..B.z"B..?B....)
  #8 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[125] ..,....."..H...m^...}`4..*.....i....K......B..........l.........$.&.>2hXg.......)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#32073)
  #10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1687): pocketmine\snooze\SleeperHandler->sleepUntil(float 1681438155.5815)
  #14 pmsrc/src/Server(1073): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[16] /home/container/, string[24] /home/container/plugins/)
  #16 pmsrc/src/PocketMine(362): pocketmine\server()
  #17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by StefanFox-Dev** [comment]
Do not use broadcastMessage, better foreach players sendMessage.

**Comment by dries-c** [comment]
This issue isn't related to any of our code, you're broadcasting a message to an array of players and one of them is not connected anymore
