### ISSUE TITLE
Bad CreativeInventory version 1.19.2, pm5 (stable)

### ISSUE THREAD

**Issue by StefanFox-Dev** [NetherGamesMC/PocketMine-MP#316]
### Issue description

- Expected result: Get normal inventory 
- Actual result: It is broken, items are scattered or doubles 2 times

### Steps to reproduce the issue
1. Open CreativeInventory
2. ...
3. 
![IMG_20230602_104706_876](https://github.com/NetherGamesMC/PocketMine-MP/assets/59245729/f6ee3135-896c-4c3d-b982-e4d009db9544)
![IMG_20230602_104658_117](https://github.com/NetherGamesMC/PocketMine-MP/assets/59245729/a6b7b2b5-188f-4e65-a76a-691e873a2655)

### OS and versions

* PocketMine-MP: 5.0.0
* PHP: 8.2
* Using JIT: no
* Server OS: Ubuntu 22.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Blackjack200** [comment]
It is not fixed.

**Comment by dries-c** [comment]
something seems to have reverted this commit, will repush
