### ISSUE TITLE
PM5 is bugged

### ISSUE THREAD

**Issue by Lunarelly** [NetherGamesMC/PocketMine-MP#321]
```TypeConverter::getInstance()->setSkinAdapter()``` affects only LATEST version
Players who are not on latest (<1.19.80) somehow got 4 sticks in crafting grid

**Comment by Lunarelly** [comment]
alright its because TypeConverter is not a single instance,

**Comment by dries-c** [comment]
getInstance() always uses the latest version. Ideally you would set this on every instance using TypeConverter::getAll(true), since the SkinAdapter might be different depending on the version of Minecraft you're using
