### ISSUE TITLE
Server crashed, pm5 (stable)

### ISSUE THREAD

**Issue by StefanFox-Dev** [NetherGamesMC/PocketMine-MP#324]
Link to crashdump: 

 pocketmine\utils\AssumptionFailedError: "Unmapped blockstate returned by blockstate serializer: TAG_Compound={ "name" => TAG_String="minecraft:lit_pumpkin" "version" => TAG_Int=18042891 "states" => TAG_Compound={ "minecraft:cardinal_direction" => TAG_String="north" } "PMMPDataVersion" => TAG_Long=1 }" (EXCEPTION) in "pmsrc/src/network/mcpe/convert/ItemTranslator" at line 133

**Comment by softlenss** [comment]
Error: Unmapped blockstate returned by blockstate serializer: TAG_Compound={ "name" => TAG_String="minecraft:acacia_log" "version" => TAG_Int=18087969 "states" => TAG_Compound={ "pillar_axis" => TAG_String="y" } "PMMPDataVersion" => TAG_Long=1 }
File: pmsrc/src/network/mcpe/convert/ItemTranslator
Line: 133
Type: pocketmine\utils\AssumptionFailedError

**Comment by Lunarelly** [comment]
Server dies when player with version <1.19.80 joining (1.19.80, 1.20 are fine)
```[Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "(560) Unmapped blockstate returned by blockstate serializer 1.20.0.33: TAG_Compound={ "name" => TAG_String="minecraft:acacia_log" "version" => TAG_Int=18087969 "states" => TAG_Compound={ "pillar_axis" => TAG_String="y" } "PMMPDataVersion" => TAG_Long=1 }" (EXCEPTION) in "pmsrc/src/network/mcpe/convert/ItemTranslator" at line 135```
Somehow all of the protocols have blockstate serializer version 1.20

**Comment by dries-c** [comment]
could you send the full stacktrace?

**Comment by Lunarelly** [comment]
you can reproduce it by joining from 1.19.70 or earlier (pm5), but ok ill send later

**Comment by StefanFox-Dev** [comment]
![bo8R_J-Tihs](https://github.com/NetherGamesMC/PocketMine-MP/assets/59245729/e926b061-519b-4d38-8d04-07893be0b2b3)

**Comment by Lunarelly** [comment]
> ![bo8R_J-Tihs](https://user-images.githubusercontent.com/59245729/244677552-e926b061-519b-4d38-8d04-07893be0b2b3.jpg)

as text idiot

**Comment by StefanFox-Dev** [comment]
+ join player in version 1.20, the server hangs forever.

**Comment by StefanFox-Dev** [comment]
the screenshot is not mine.

**Comment by StefanFox-Dev** [comment]
In addition, the player can be use version < 1.18.30 — server crashed because of Mangroves.

**Comment by Lunarelly** [comment]
> * join player in version 1.20, the server hangs forever.

1.20 works fine

**Comment by StefanFox-Dev** [comment]
xd, after sunset, it’s stupid for me to go to bed like sleep(999999)😁

original pm5 - everything is fine, nothing like that.

**Comment by Lunarelly** [comment]
what are u talkin about lol

**Comment by StefanFox-Dev** [comment]
Давай на русском.

**Comment by Blackjack200** [comment]
> could you send the full stacktrace?

 @dries-c 

[Fri_Jun_9-22.40.51-CST_2023.log](https://github.com/NetherGamesMC/PocketMine-MP/files/11707375/Fri_Jun_9-22.40.51-CST_2023.log)


and this patch can make lower player join but not properly (some item is wrong)
and in this version, creative inventories messed up again.


```patch
diff --git a/src/network/mcpe/convert/BlockTranslator.php b/src/network/mcpe/convert/BlockTranslator.php
index df3252d3b..4a809d09c 100644
--- a/src/network/mcpe/convert/BlockTranslator.php
+++ b/src/network/mcpe/convert/BlockTranslator.php
@@ -144,7 +144,8 @@ final class BlockTranslator{
 
 			$networkId = $this->blockStateDictionary->lookupStateIdFromData($blockStateData);
 			if($networkId === null){
-				throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
+				return $this->networkIdCache[$internalStateId] = $networkId;
+				//throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
 			}
 		}catch(BlockStateSerializeException){
 			//TODO: this will swallow any error caused by invalid block properties; this is not ideal, but it should be
diff --git a/src/network/mcpe/convert/ItemTranslator.php b/src/network/mcpe/convert/ItemTranslator.php
index 042e176d2..0606d1e6a 100644
--- a/src/network/mcpe/convert/ItemTranslator.php
+++ b/src/network/mcpe/convert/ItemTranslator.php
@@ -130,7 +130,8 @@ final class ItemTranslator{
 
 			$blockRuntimeId = $this->blockTranslator->getBlockStateDictionary()->lookupStateIdFromData($blockStateData);
 			if($blockRuntimeId === null){
-				throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
+				$blockRuntimeId = self::NO_BLOCK_RUNTIME_ID;
+				//throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
 			}
 		}else{
 			$blockRuntimeId = self::NO_BLOCK_RUNTIME_ID; //this is technically a valid block runtime ID, but is used to represent "no block" (derp mojang)
```

**Comment by Lunarelly** [comment]
```if($blockRuntimeId === null){
-				throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
+				$blockRuntimeId = self::NO_BLOCK_RUNTIME_ID;
+				//throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
 			}```
 			
 i tried this too, but it just spams in log then

**Comment by Lunarelly** [comment]
its not a proper solution anyway

**Comment by Blackjack200** [comment]
after some investigation, I think it is because of block name is not downgraded properly
see: 
 current: oak_log
 translated: oak_log
 wanted: log

**Comment by Blackjack200** [comment]
maybe the implementation of BlockStateDowngrader has something wrong

**Comment by Blackjack200** [comment]
i had fixed that but with insuffient test.

**Comment by ZukerDev** [comment]
Does your fix work?

**Comment by ZukerDev** [comment]
If not, could you tell me how you managed to fix it?

**Comment by Blackjack200** [comment]
> If not, could you tell me how you managed to fix it?

work properly, and just see the PR

**Comment by dries-c** [comment]
Can you send the crashdump in text? the image isn't readable

**Comment by StefanFox-Dev** [comment]
> > could you send the full stacktrace?
> 
> @dries-c
> 
> [Fri_Jun_9-22.40.51-CST_2023.log](https://github.com/NetherGamesMC/PocketMine-MP/files/11707375/Fri_Jun_9-22.40.51-CST_2023.log)
> 
> and this patch can make lower player join but not properly (some item is wrong) and in this version, creative inventories messed up again.
> 
> ```diff
> diff --git a/src/network/mcpe/convert/BlockTranslator.php b/src/network/mcpe/convert/BlockTranslator.php
> index df3252d3b..4a809d09c 100644
> --- a/src/network/mcpe/convert/BlockTranslator.php
> +++ b/src/network/mcpe/convert/BlockTranslator.php
> @@ -144,7 +144,8 @@ final class BlockTranslator{
>  
>  			$networkId = $this->blockStateDictionary->lookupStateIdFromData($blockStateData);
>  			if($networkId === null){
> -				throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
> +				return $this->networkIdCache[$internalStateId] = $networkId;
> +				//throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
>  			}
>  		}catch(BlockStateSerializeException){
>  			//TODO: this will swallow any error caused by invalid block properties; this is not ideal, but it should be
> diff --git a/src/network/mcpe/convert/ItemTranslator.php b/src/network/mcpe/convert/ItemTranslator.php
> index 042e176d2..0606d1e6a 100644
> --- a/src/network/mcpe/convert/ItemTranslator.php
> +++ b/src/network/mcpe/convert/ItemTranslator.php
> @@ -130,7 +130,8 @@ final class ItemTranslator{
>  
>  			$blockRuntimeId = $this->blockTranslator->getBlockStateDictionary()->lookupStateIdFromData($blockStateData);
>  			if($blockRuntimeId === null){
> -				throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
> +				$blockRuntimeId = self::NO_BLOCK_RUNTIME_ID;
> +				//throw new AssumptionFailedError("Unmapped blockstate returned by blockstate serializer: " . $blockStateData->toNbt());
>  			}
>  		}else{
>  			$blockRuntimeId = self::NO_BLOCK_RUNTIME_ID; //this is technically a valid block runtime ID, but is used to represent "no block" (derp mojang)
> ```

here.

**Comment by StefanFox-Dev** [comment]
> i had fixed that but with insuffient test.

**Dries-c**, Here the person has already provided a fix, I propose to close this issues and install a fix person.

**Comment by dries-c** [comment]
It's not a proper fix

**Comment by dries-c** [comment]
Could you provide me with which version you're testing this with?

**Comment by dries-c** [comment]
This issue is caused by some things not being properly downgraded it seems

**Comment by StefanFox-Dev** [comment]
addItem(object pocketmine\item\ItemBlock#147751)
= crash.
A player with a previous fix - can enter until he gives out the item.

**Comment by StefanFox-Dev** [comment]
Join - good, no crash

**Comment by StefanFox-Dev** [comment]
![Screenshot_20230616-191815_Minecraft](https://github.com/NetherGamesMC/PocketMine-MP/assets/59245729/cf3b841a-f34c-4a64-ae94-19be70e67092)
everything works except chunks and blocks...

**Comment by dries-c** [comment]
eh? with what version? i'm so confused. You didn't answer my question: 
Could you provide me with which version you're testing this with?

**Comment by StefanFox-Dev** [comment]
1.18.10

**Comment by StefanFox-Dev** [comment]
used fix #332

**Comment by dries-c** [comment]
Instead of downgrading, i'm rewriting the system to only use upgrading so the items that aren't supported don't appear.

**Comment by RimashevskyDev** [comment]
When logging in from version 1.19.63, it also causes a crash

**Comment by ghost** [comment]
Server crash when logging in from 1.19.x and 1.18.x versions

**Comment by dries-c** [comment]
There the update is, have fun!
