### ISSUE TITLE
Item fromNetworkId

### ISSUE THREAD

**Issue by Fadhilarsetya** [NetherGamesMC/PocketMine-MP#340]
Error: Invalid network itemstack data: Unknown block ID "minecraft:log"
File: pmsrc/src/network/mcpe/convert/TypeConversionException
Line: 33
Type: pocketmine\network\mcpe\convert\TypeConversionException
Backtrace:
#0 pmsrc/src/network/mcpe/convert/ItemTranslator(194): pocketmine\network\mcpe\convert\TypeConversionException::wrap(object pocketmine\data\bedrock\item\UnsupportedItemTypeException#90936, string[30] Invalid network itemstack data)
#1 pmsrc/src/network/mcpe/convert/TypeConverter(234): pocketmine\network\mcpe\convert\ItemTranslator->fromNetworkId(int 17, int 0, int 10524)

**Comment by Blackjack200** [comment]
how can we reproduce that

**Comment by Fadhilarsetya** [comment]
> Use TypeConverter netItemStackToCore, my minecraft version is 1.19.70

**Comment by dries-c** [comment]
You've to include the entire stacktrace. What you reported is useless by itself
