### ISSUE TITLE
PM5, join with 1.19.80, disconnect immediately

### ISSUE THREAD

**Issue by Blackjack200** [NetherGamesMC/PocketMine-MP#347]
### Issue description
no error. but.
- Expected result: Join the server
- Actual result: The client "disconnected from the server"

### Steps to reproduce the issue
1. checkout the latest PM5 branch
2. join with 1.19.80

### OS and versions

* PocketMine-MP: ffefa249334b260e1a6b4c54f843cea72dd9164e
* Game version: Android/iOS/Win10

**Comment by dries-c** [comment]
Do other versions work?
