### ISSUE TITLE
Server crashed when player joins the server 

### ISSUE THREAD

**Issue by Kingom1** [NetherGamesMC/PocketMine-MP#348]
![Screenshot_٢٠٢٣٠٦٢٤-١٩٣٥٣٥](https://github.com/NetherGamesMC/PocketMine-MP/assets/102631520/af8bb836-55a3-4d3c-94dd-7e58e3715706)

Link to crashdump:

**Comment by dries-c** [comment]
You've reached your storage or memory limit
