### ISSUE TITLE
Crafting Table bug

### ISSUE THREAD

**Issue by UnknownNull** [NetherGamesMC/PocketMine-MP#353]
### Steps to reproduce the issue
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/91208232/a5d916ed-2e38-4825-a0e9-a9a806f23fcb)
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/91208232/055ba2a5-34f2-4789-9914-b5c212e8e6e6)

### OS and versions
* PocketMine-MP: 5.1.3
* PHP: 8.2
* Using JIT: yes/no (delete as appropriate) 
* Server OS: windows
* Game version: Android/Win10

### Plugins
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/91208232/c39a568e-703a-4e6a-9b54-170e4a402c25)

**Comment by dries-c** [comment]
I'm aware, however I've no clue what causes this

**Comment by labarjni** [comment]
Check out this commit https://github.com/DavyCraft648/PM-NG/commit/8c7c52d49b509db85935f3b98f6b3fa1e4d437c7
Maybe there is a solution there

> I'm aware, however I've no clue what causes this

**Comment by dries-c** [comment]
It's an issue where TagWildcardRecipeIngredient doesn't work below 1.19.30. I'm thinking of a way to implement this, but I just removed the implementation for now.

**Comment by UnknownNull** [comment]
and... in 1.20
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/91208232/3d9298d8-cc92-4f12-8809-fa1c0eb7a5a7)

**Comment by dries-c** [comment]
No longer an issue as the version has been dropped

**Comment by UnknownNull** [comment]
> No longer an issue as the version has been dropped

Wouldn't it be better not to delete the previous versions?
