### ISSUE TITLE
default permission bug

### ISSUE THREAD

**Issue by UnknownNull** [NetherGamesMC/PocketMine-MP#360]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
The default perms are not loaded in the lower versions like 1.19.10 and if the account is opened, the person will leave the server and cannot return.

### OS and versions
* PocketMine-MP: 5.1.3
* PHP: 8.2
* Using JIT: no 
* Server OS: windows
* Game version: Win10 119.10

### Plugins
ranksystem

The system seems to work well without the Rank plugin

### Crashdump, backtrace or other files
nothing or sho close server msg but not crashed server

**Comment by Nisekoi6800** [comment]
same issue with RankSystem & MultiWorld plugins.

**Comment by dries-c** [comment]
i'm confused as to what the actual issue is here, I didn't modify anything related to permissions

**Comment by UnknownNull** [comment]
I guess the problem is with RankSystem,
