### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by AraaCuteUwU** [NetherGamesMC/PocketMine-MP#369]
Server thread/CRITICAL]: pocketmine\data\SavedDataLoadingException: "Missing firework data" (EXCEPTION) in "pmsrc/src/item/FireworkRocket" at line 145
--- Stack trace ---
  #0 pmsrc/src/item/Item(266): pocketmine\item\FireworkRocket->deserializeCompoundTag(object pocketmine\nbt\tag\CompoundTag#422703)
  #1 pmsrc/src/data/bedrock/item/ItemDeserializer(101): pocketmine\item\Item->setNamedTag(object pocketmine\nbt\tag\CompoundTag#434139)
  #2 pmsrc/src/item/Item(721): pocketmine\data\bedrock\item\ItemDeserializer->deserializeStack(object pocketmine\data\bedrock\item\SavedItemStackData#386461)
  #3 pmsrc/src/entity/Human(307): pocketmine\item\Item::nbtDeserialize(object pocketmine\nbt\tag\CompoundTag#362878)
  #4 pmsrc/src/player/Player(348): pocketmine\entity\Human->initEntity(object pocketmine\nbt\tag\CompoundTag#415292)
  #5 pmsrc/src/entity/Entity(220): pocketmine\player\Player->initEntity(object pocketmine\nbt\tag\CompoundTag#415292)
  #6 pmsrc/src/entity/Human(121): pocketmine\entity\Entity->__construct(object pocketmine\entity\Location#363844, object pocketmine\nbt\tag\CompoundTag#415292)
  #7 pmsrc/src/player/Player(330): pocketmine\entity\Human->__construct(object pocketmine\entity\Location#363844, object pocketmine\entity\Skin#384058, object pocketmine\nbt\tag\CompoundTag#415292)
  #8 pmsrc/src/Server(584): pocketmine\player\Player->__construct(object pocketmine\Server#13, object pocketmine\network\mcpe\NetworkSession#369558, object pocketmine\player\XboxLivePlayerInfo#432014, true, object pocketmine\entity\Location#363844, object pocketmine\nbt\tag\CompoundTag#415292)
  #9 pmsrc/src/Server(608): pocketmine\Server->pocketmine\{closure}(object pocketmine\entity\Location#363844)
  #10 pmsrc/src/network/mcpe/NetworkSession(253): pocketmine\Server->createPlayer(object pocketmine\network\mcpe\NetworkSession#369558, object pocketmine\player\XboxLivePlayerInfo#432014, true, object pocketmine\nbt\tag\CompoundTag#415292)
  #11 pmsrc/src/network/mcpe/NetworkSession(886): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #12 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(144): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #13 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#294318)
  #14 pmsrc/src/network/mcpe/NetworkSession(512): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#431292)
  #15 pmsrc/src/network/mcpe/NetworkSession(455): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#294318, string[4] ....)
  #16 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
  #17 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 15, string[16] ....P(....5k.M#$)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#177103)
  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #20 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #22 pmsrc/src/Server(1687): pocketmine\snooze\SleeperHandler->sleepUntil(float 1689305768.5544)
  #23 pmsrc/src/Server(1075): pocketmine\Server->tickProcessor()
  #24 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[13] /root/server/, string[21] /root/server/plugins/)
  #25 pmsrc/src/PocketMine(357): pocketmine\server()
  #26 pmsrc(11): require(string[57] phar:///root/server/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by IvanCraft623** [comment]
You were using some plugin or something with a bad fireworks implementation.
