### ISSUE TITLE
Crafting < 1.19.60 not working

### ISSUE THREAD

**Issue by radovinetch** [NetherGamesMC/PocketMine-MP#381]
### Issue description

- Expected result: I try to craft item via shapeless inventory and it worked on 1.18.31
- Actual result: I try to craft item via shapeless inventory and it doesn't worked

### Steps to reproduce the issue
1. Install 1.18.31 (but i tested it on 1.19.20 and 1.19.0 and crafts also doesn't work).
2. Open shapeless crafting grid and try to craft.
3. Crafts don't work

### OS and versions
* Core version: 5.3.3-dev: 
* PHP: 8.1.20
* Game version: Win10

### Plugins
Don't have any plugins. This issue reproduces also without plugins.

- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files
https://pastebin.com/NaYmkkUV when i try to craft with debug level > 1 i get this messages in console.

**Comment by dries-c** [comment]
No longer an issue as the version has been dropped
