### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Kingom1** [NetherGamesMC/PocketMine-MP#403]
Why pm4 is not working

**Comment by dries-c** [comment]
It does work, since we run it on production at NetherGames. Do you've a crashdump?

**Comment by Kingom1** [comment]
![Screenshot_-](https://github.com/NetherGamesMC/PocketMine-MP/assets/102631520/bb8b5bf4-7cca-46b5-a766-392f88c42698)
Note: I have a large space and it appears like this. When I set it to pm5, it works normally. When I set it to pm4, it shows like this

**Comment by dries-c** [comment]
This doesn't include the actual error, it's a line above this one

**Comment by Kingom1** [comment]
![Uploading Screenshot_-.png…]()

**Comment by Kingom1** [comment]
is there a solution?

**Comment by Kingom1** [comment]
![Uploading Screenshot_٢٠٢٣٠٩٢٩-١٦٢٦٠٣.png…]()

**Comment by dries-c** [comment]
Invalid screenshot sadly

**Comment by Kingom1** [comment]
I mean, there is a solution to my problem. When I use pm5, it works normally, but when I set it to pm4, it appears like the picture above.

**Comment by dries-c** [comment]
<img width="947" alt="image" src="https://github.com/NetherGamesMC/PocketMine-MP/assets/15795262/807bb33b-4bc3-44cd-91a8-c184a270044d">
This screenshot doesn't load for me, I can't debug it without seeing the actual error

**Comment by Kingom1** [comment]
![Screenshot_-](https://github.com/NetherGamesMC/PocketMine-MP/assets/102631520/18a5ecc4-f106-4d13-abe8-16c23884efd9)

**Comment by dries-c** [comment]
Seems like your world is corrupt, it's not our fault.

**Comment by Kingom1** [comment]
So give me a solution
