### ISSUE TITLE
Wrong display in item frame

### ISSUE THREAD

**Issue by UnknownNull** [NetherGamesMC/PocketMine-MP#405]
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/91208232/57c63368-ae32-4f20-9f2b-78a74bda0c35)

Colored glass and colored concrete are displayed in the item frame in this way

**Comment by dries-c** [comment]
Uhh, yeah.. uh

**Comment by dries-c** [comment]
Should be fixed now

**Comment by UnknownNull** [comment]
> Should be fixed now

![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/91208232/8f8491bc-2e9b-47a1-8725-2eaa7b57aff7)
bruh. new wrong

**Comment by UnknownNull** [comment]
> ![image](https://private-user-images.githubusercontent.com/91208232/275544045-57c63368-ae32-4f20-9f2b-78a74bda0c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjc2OTAsIm5iZiI6MTcwNDAyNzM5MCwicGF0aCI6Ii85MTIwODIzMi8yNzU1NDQwNDUtNTdjNjMzNjgtYWUzMi00ZjIwLTlmMmItNzhhNzRiZGEwYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDEyNTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOGVhZTUyMTM1MjRlNmExOTA2NDg1MmM0MTUyZGM2MWY3MThlMTIwNzU5NTYzYmFjOGVhZDYwMzllOTNhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l6kTiz_US59Xyfr7SLZv7O6oT2OEH0WlN7A6HAcsugc)
> 
> Colored glass and colored concrete are displayed in the item frame in this way

again @dries-c
