### ISSUE TITLE
Server crashed after join players

### ISSUE THREAD

**Issue by UnknownNull** [NetherGamesMC/PocketMine-MP#406]
2023-10-27 [05:16:42.984] [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Unmapped blockstate returned by blockstate serializer: TAG_Compound={ "name" => TAG_String="minecraft:chest" "version" => TAG_Int=18098179 "states" => TAG_Compound={ "minecraft:cardinal_direction" => TAG_String="north" } "PMMPDataVersion" => TAG_Long=1 }" (EXCEPTION) in "pmsrc/src/network/mcpe/convert/ItemTranslator" at line 89
--- Stack trace ---
  #0 pmsrc/src/network/mcpe/convert/ItemTranslator(61): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkId(object pocketmine\item\ItemBlock#1359368)
  #1 pmsrc/src/network/mcpe/convert/TypeConverter(219): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkIdQuiet(object pocketmine\item\ItemBlock#1359368)
  #2 pmsrc/src/network/mcpe/cache/CreativeInventoryCache(64): pocketmine\network\mcpe\convert\TypeConverter->coreItemStackToNet(object pocketmine\item\ItemBlock#1359368)
  #3 pmsrc/src/network/mcpe/cache/CreativeInventoryCache(51): pocketmine\network\mcpe\cache\CreativeInventoryCache->buildCreativeInventoryCache(object pocketmine\inventory\CreativeInventory#42823)
  #4 pmsrc/src/network/mcpe/InventoryManager(643): pocketmine\network\mcpe\cache\CreativeInventoryCache->getCache(object pocketmine\inventory\CreativeInventory#42823)
  #5 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(146): pocketmine\network\mcpe\InventoryManager->syncCreative()
  #6 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\handler\PreSpawnPacketHandler->setUp()
  #7 pmsrc/src/network/mcpe/NetworkSession(894): pocketmine\network\mcpe\NetworkSession->setHandler(object pocketmine\network\mcpe\handler\PreSpawnPacketHandler#1369443)
  #8 pmsrc/src/network/mcpe/NetworkSession(309): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
  #9 pmsrc/src/promise/Promise(47): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#1372448)
  #10 pmsrc/src/network/mcpe/NetworkSession(246): pocketmine\promise\Promise->onCompletion(object Closure#1372452, object Closure#1372451)
  #11 pmsrc/src/network/mcpe/NetworkSession(889): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #12 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(144): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #13 pmsrc/vendor/arabskills/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#49391)
  #14 pmsrc/src/network/mcpe/NetworkSession(514): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#179721)
  #15 pmsrc/src/network/mcpe/NetworkSession(452): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#49391, string[4] ....)
  #16 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
  #17 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[8] .c.`a`..)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#43834)
  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #20 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #22 pmsrc/src/Server(1708): pocketmine\snooze\SleeperHandler->sleepUntil(float 1698383802.8098)
  #23 pmsrc/src/Server(1090): pocketmine\Server->tickProcessor()
  #24 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[52] C:\Users\Administrator\Documents\MV - RL\2.survival\, string[60] C:\Users\Administrator\Documents\MV - RL\2.survival\plugins\)
  #25 pmsrc/src/PocketMine(357): pocketmine\server()
  #26 pmsrc(11): require(string[96] phar://C:/Users/Administrator/Documents/MV - RL/2.survival/PocketMine-MP.phar/sr)

**Comment by dries-c** [comment]
Could you help us reproduce it by giving us information about what happened

**Comment by UnknownNull** [comment]
> Could you help us reproduce it by giving us information about what happened

Every player that joins the server causes the server to crash (that's all).

**Comment by UnknownNull** [comment]
I fixed it for myself
