### ISSUE TITLE
Error with CraftingEventPacket

### ISSUE THREAD

**Issue by labarjni** [NetherGamesMC/PocketMine-MP#410]
### Issue description
The error is related to the removal of CraftingEventPacket on versions below 1.20.50

### Steps to reproduce the issue
1. Attempting to craft an item
2. An error occurs: Bad packet: Unknown packet received

### OS and versions

* PocketMine-MP: 5.9.1
* PHP: 8.2
* Using JIT: no
* Server OS: win
* Game version: 1.20.12 (Protocol 594)

### Plugins
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/83462236/4f67f0bc-917d-4b22-8c61-96b733fc6e15)

### Crashdump, backtrace or other files
![2023-12-07 00-57-46 (online-video-cutter com)](https://github.com/NetherGamesMC/PocketMine-MP/assets/83462236/d60d71e8-15ed-47f3-8395-e0fac790e3b2)
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/83462236/f12245e0-033d-4ff1-bbc8-4d8048f536de)

**Comment by UnknownNull** [comment]
This can be a bad problem, but I think that if you test with the latest version, 1.20.50, this problem will not exist.

**Comment by UnknownNull** [comment]
I think ...
https://github.com/pmmp/BedrockProtocol/commit/2a98eb7fabbb4472263cb24c10286b6462fcdcf1#diff-a63e2e74317d3b94ebba8905470e8fc0e7f89d52cba4366bc46e724393ca987eL93
#409

**Comment by dries-c** [comment]
This packet has been readded
