### ISSUE TITLE
Please fix opening the backpack 1.20.50 Collapse

### ISSUE THREAD

**Issue by QYEnote** [NetherGamesMC/PocketMine-MP#411]
[10:44:16.314] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: sb
[10:44:16.315] [Server thread/CRITICAL]: Error: "Class "pocketmine\network\mcpe\protocol\types\inventory\InventoryLeftTab" not found" (EXCEPTION) in "pmsrc/vendor/nethergamesmc/bedrock-protocol/src/SetPlayerInventoryOptionsPacket" at line 55
--- Stack trace ---
  #0 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/DataPacket(52): pocketmine\network\mcpe\protocol\SetPlayerInventoryOptionsPacket->decodePayload(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#42903)
  #1 pmsrc/src/network/mcpe/NetworkSession(463): pocketmine\network\mcpe\protocol\DataPacket->decode(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#42903)
  #2 pmsrc/src/network/mcpe/NetworkSession(425): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetPlayerInventoryOptionsPacket#104131, string[7] .......)
  #3 pmsrc/src/network/mcpe/raklib/RakLibInterface(188): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[53] c.......`7........14.8|...G...N.P..ohh.`bbr...&,.....)
  #4 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[54] .c.......`7........14.8|...G...N.P..ohh.`bbr...&,.....)
  #5 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#33042)
  #6 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #7 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #9 pmsrc/src/Server(1699): pocketmine\snooze\SleeperHandler->sleepUntil(float 1702205056.359)
  #10 pmsrc/src/Server(1085): pocketmine\Server->tickProcessor()
  #11 pmsrc/src/PocketMine(336): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[31] D:\rank......\10.3qos - ......\, string[39] D:\rank......\10.3qos - ......\plugins\)
  #12 pmsrc/src/PocketMine(359): pocketmine\server()
  #13 pmsrc(11): require(string[75] phar://D:/rank....../10.3qos - ....../PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[10:44:16.315] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[10:44:16.321] [Server thread/EMERGENCY]: Please upload the "D:/rank设置/10.3qos - 副本/crashdumps/Sun_Dec_10-10.44.16-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[10:44:16.322] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by QYEnote** [comment]
1.20.50 A crash occurred when opening the backpack
legacy pm4

**Comment by dries-c** [comment]
What's a backpack?

**Comment by QYEnote** [comment]
1.20.50 bedrock The player opens the inventory server crashed

**Comment by dries-c** [comment]
**https://github.com/NetherGamesMC/BedrockProtocol/blob/master/src/types/inventory/InventoryLeftTab.php**
clearly exists, try cloning again
