### ISSUE TITLE
The Chiseled Bookshelf block causes a crash on client version 1.20.40.

### ISSUE THREAD

**Issue by Kepler139f** [NetherGamesMC/PocketMine-MP#413]
### Issue description

- Expected result: The player must log into the server.
- Actual result: Due to the Chiseled Bookshelf block on version 1.20.40 the client crashes.

### Steps to reproduce the issue
1. Join the server with a friend. The friend must have version 1.20.40.
2. Place the Chiseled Bookshelf block next to a friend.
3. Ask your friend to leave the server.
4. Done. Your friend will no longer be able to log in until you remove the Chiseled Bookshelf block.

### OS and versions
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/59138462/8d44e529-b042-40ad-8dd8-efeb7907f1a0)
Game version: Android 1.20.40

### Plugins
![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/59138462/21cc9cfb-1215-4a32-b8e4-63f6273a0e7d)

![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/59138462/19b34527-666a-4fbb-b855-a409513ec5ce)

**Comment by dries-c** [comment]
Chiseled bookshelfs work just fine on 1.20.40 according to my findings
