### ISSUE TITLE
Enchant Books not set in Anvil

### ISSUE THREAD

**Issue by UnknownNull** [NetherGamesMC/PocketMine-MP#447]
Some Enchant Books like `unberking` are not set on items in `Anvil`

**Comment by dries-c** [comment]
Does PM support them?

**Comment by UnknownNull** [comment]
> Does PM support them?
pmmp has added the enchant it supports (But again, I have not tested it exactly)

**Comment by dries-c** [comment]
Could you test it and let me know? if it works for the official repo, i'll take a look

**Comment by dries-c** [comment]
Closed due to inactivity

**Comment by UnknownNull** [comment]
> Could you test it and let me know? if it works for the official repo, i'll take a look

Apparently, this cannot be done in official either, but the update log they provided says something else
