### ISSUE TITLE
Fix World Y min

### ISSUE THREAD

**Issue by 6kek6** [NetherGamesMC/PocketMine-MP#463]
https://github.com/NetherGamesMC/PocketMine-MP/blob/2398a0ec9255de1c8188bff0e23ebd61ec834a2e/src/entity/Entity.php#L659

This has been fixed in pmmp - https://github.com/pmmp/PocketMine-MP/blob/9b6a0c99450949c4350f5d3bf49396c19e6ce79c/src/entity/Entity.php#L657

**Comment by StefanFox-Dev** [comment]
@dries-c

**Comment by dries-c** [comment]
Well at NG we don't use this feature, that's why it's this way. When I've the time I'll make it configurable

**Comment by 6kek6** [comment]
> Well at NG we don't use this feature, that's why it's this way. When I've the time I'll make it configurable

Fine.

**Comment by dries-c** [comment]
You can make a PR if you find the time.
