### ISSUE TITLE
Error join version < 1.20.60

### ISSUE THREAD

**Issue by StefanFox-Dev** [NetherGamesMC/PocketMine-MP#464]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Bad packet: Unknown packet received (ID: ab82-f71f-d315)

### OS and versions

* PocketMine-MP: 5.16.1
* PHP: 8.2
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by UnknownNull** [comment]
@dries-c
