### ISSUE TITLE
Stairs can't place in one direction

### ISSUE THREAD

**Issue by Woof9999** [NetherGamesMC/PocketMine-MP#467]
### Issue description

- Expected result: Place stair and it face towards me
- Actual result: Place stair and it face away from me

### Steps to reproduce the issue
1. Place stairs

### OS and versions
 1.21
* PocketMine-MP: 5.16.1+dev
* PHP: 8.2.17
* Using JIT: yes/no (delete as appropriate)  no
* Server OS: linux
* Game version: Win 10 (delete as appropriate)

### Plugins

Bedwars, BuilderTools, Devirion DevTools, MultiWorld, Customkb
- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![image](https://github.com/NetherGamesMC/PocketMine-MP/assets/84981018/755e71ed-3151-4510-8cec-44b66737d911)

**Comment by dries-c** [comment]
Which version of minecraft are you using?

**Comment by dries-c** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/af2e7404-0600-4196-bc19-5f757723e69b">
Can't reproduce on 1.20.51
