### ISSUE TITLE
Error in any pterodactyl host (tried only with Witherhosting & Mcchosting)

### ISSUE THREAD

**Issue by ItsToxicGG** [NetherGamesMC/PocketMine-MP#469]
### Issue description

Basically when i use normal pocketmine it works fine, but when i use ng's one, i get the same issue, this error does not
occur when hosting local.

- Expected result: What were you expecting to happen?

It starts the server like normal 

- Actual result: What actually happened?
Getting this error:

:/home/container$ ./start.sh
Preparing PocketMine-MP.phar decompressed cache...
Notice: Phar::convertToData(): Write of 8192 bytes failed with errno=28 No space left on device in /home/container/PocketMine-MP.phar on line 118
Notice: Phar::convertToData(): Write of 1024 bytes failed with errno=28 No space left on device in /home/container/PocketMine-MP.phar on line 118
Fatal error: Uncaught BadMethodCallException: tar-based phar "/tmp/PocketMine-MP-phar-cache.0/PMMPZJYA2g.tar" cannot be created, contents of file "vendor/nethergamesmc/bedrock-data/required_item_list-1.20.80.json" could not be written in /home/container/PocketMine-MP.phar:118
Stack trace:
#0 /home/container/PocketMine-MP.phar(118): Phar->convertToData(2, 0)
#1 /home/container/PocketMine-MP.phar(158): pocketmine\server_phar_stub\convertPharToTar('/tmp/PocketMine...', '/home/container...')
#2 /home/container/PocketMine-MP.phar(165): pocketmine\server_phar_stub\preparePharCache('/tmp/PocketMine...', '/home/container...')
#3 {main}
  thrown in /home/container/PocketMine-MP.phar on line 118

### Steps to reproduce the issue
1. Start the server with a host like witherhosting

### OS and versions

* PocketMine-MP: Latest
* PHP: 8.3.0 or 8.2.0
* Using JIT: no
* Server OS: Linux
* Game version: 1.21.2

### Plugins
Invalid as this is when i start the server and it does not load any plugins.

**Comment by dries-c** [comment]
There's not enough space on your disk

**Comment by ItsToxicGG** [comment]
but i got 4 gb's still left

**Comment by ItsToxicGG** [comment]
so i dont understand, however i just fixed the issue aswell i was aboutta close this
