### ISSUE TITLE
Packet perocessing error

### ISSUE THREAD

**Issue by TheAryqn** [NetherGamesMC/PocketMine-MP#471]
When a player wants to join to the server with <1.20.60 version, he gets kicked from the server and shows this error for him.
![IMG_20240715_122609_316](https://github.com/user-attachments/assets/a8c3b8b5-8837-4ad4-a698-fbdb45355c4f)

**Comment by dries-c** [comment]
Could you send the error the server displays whenever this happens?

**Comment by TheAryqn** [comment]
> Could you send the error the server displays whenever this happens?

![Screenshot_20240715_171001_Microsoft Remote Desktop](https://github.com/user-attachments/assets/0bb16a1c-6533-472b-bd29-8f003f999e89)

**Comment by dries-c** [comment]
And it's with every version above 1.20.60?

**Comment by TheAryqn** [comment]
> And it's with every version above 1.20.60?

No, version 1.20.60 and below

**Comment by dries-c** [comment]
Can't reproduce this issue on 1.20.51
