### ISSUE TITLE
BlockData

### ISSUE THREAD

**Issue by pmCraftiR** [NetherGamesMC/PocketMine-MP#472]
when i create a item and register it with plugin [Customies ](https://github.com/CustomiesDevs/Customies/) it's not register for older versions and show block update.
for example in 1.20.0 until 1.21.0 just item texture show in 1.21.0 in older versions its show block update

**Comment by dries-c** [comment]
https://github.com/CustomiesDevs/Customies/blob/master/src/item/CustomiesItemFactory.php#L100C17-L100C30 This has to be initiated for each version you want players to use.
