### ISSUE TITLE
Freezes core

### ISSUE THREAD

**Issue by 6kek6** [NetherGamesMC/PocketMine-MP#479]
### Issue description

Previously I wrote about server freezes for no reason, but in the end I found the problem using debug symbols. The screenshots will provide all the technical information about the problem, there will be no player intervention, all functions were called by the server as usual. In debug these are the last logs, then the server hangs forever, or until the process is killed

### OS and versions

* PocketMine-MP: 5.17.2 (last)
* PHP: 8.2
* Using JIT: no
* Server OS: Ubuntu 20.04
![Screenshot_20240823_134445](https://github.com/user-attachments/assets/d1fde71e-7ab4-42a4-aa6f-420bd27d3123)
![1724391454496](https://github.com/user-attachments/assets/b14d5523-e746-4e40-9671-24c8fcfb439b)
![Screenshot_20240823_101300_com mojang minecraftpe_edit_108618463746445](https://github.com/user-attachments/assets/ec62db4d-81f2-4c6f-92c1-a613095aa9c5)

**Comment by StefanFox-Dev** [comment]
![SmartSelect_20240825-212940_Termius](https://github.com/user-attachments/assets/cbb73674-e52d-4bd2-a9f1-f4d83ef714da)
something like this, right?

**Comment by 6kek6** [comment]
> ![SmartSelect_20240825-212940_Termius](https://private-user-images.githubusercontent.com/59245729/361252009-cbb73674-e52d-4bd2-a9f1-f4d83ef714da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTE0ODMsIm5iZiI6MTcyNDY1MTE4MywicGF0aCI6Ii81OTI0NTcyOS8zNjEyNTIwMDktY2JiNzM2NzQtZTUyZC00YmQyLWE5ZjEtZjRkODNlZjcxNGRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA1NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZWUwNDk4N2NkYjdiN2QwNmRhOWQ0ZTY2YTI1YjMxZDUwODM0OGU4NTRjZGEwMzdkNjdhNTcyNDE3YTliOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tufaeghCw_5IdFqIK6bXq7mk9lNF0QIiCLtzTPvuURg) something like this, right?

Yes

**Comment by dries-c** [comment]
A freeze looks like a freeze, so that doesn't surprise me. I just want to know if it happens using PMMP

**Comment by StefanFox-Dev** [comment]
> Заморожування виглядає як заморожування, тому мене це не дивує. Я просто хочу знати, чи це відбувається за допомогою PMMP

3 players (place blocks, break, run, pvp, write in chat) equipment AMD RYZEN 9 7950X (16 cores, 32GB RAM) version: original PM. (this was noticed by ME personally since version 1.17.0 pm3)

**Comment by dries-c** [comment]
The thread should be moved to the PMMP repo then.
