### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by DeadZeta** [NetherGamesMC/PocketMine-MP#484]
Link to crashdump:  https://pastebin.com/VL4mRHn4
Used latest commit: [Fix #482](https://github.com/NetherGamesMC/PocketMine-MP/commit/f183ccc7c038e39b637144b4f899a16e2b0fea21)

**Comment by dries-c** [comment]
https://github.com/NetherGamesMC/BedrockData/blob/master/canonical_block_states-1.21.20.nbt
Try to reinstall the composer dependencies
