### ISSUE TITLE
The chest cannot be opened 

### ISSUE THREAD

**Issue by nzAily** [NetherGamesMC/PocketMine-MP#489]
![image](https://github.com/user-attachments/assets/0f39f4e5-b561-4a98-80a2-73233dcee3a0)
I am using minecraft version 1.21.22, and the latest software

**Comment by nzAily** [comment]
![image](https://github.com/user-attachments/assets/8c7ce0ce-b61d-4e4b-a865-ea411ea2bc55)
and suddenly a block appears randomly

**Comment by GameParrot** [comment]
Can you reproduce without plugins?

**Comment by dries-c** [comment]
Can't reproduce
