### ISSUE TITLE
IIRC, Entity should use new UpdateAttribute

### ISSUE THREAD

**Issue by Yexeed** [NetherGamesMC/PocketMine-MP#490]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

https://github.com/NetherGamesMC/PocketMine-MP/blob/stable/src/entity/Entity.php#L54
```php
use pocketmine\network\mcpe\protocol\types\entity\Attribute as NetworkAttribute; // <<-- \entity\Attribute is not exist anymore, right?
```
https://github.com/NetherGamesMC/PocketMine-MP/blob/stable/src/entity/Entity.php#L1502
```php
$this->location->yaw, //TODO: body yaw (wtf mojang?)
array_map(function(Attribute $attr) : NetworkAttribute{ //same here (NetworkAttribute doesnt exist)
    return new NetworkAttribute($attr->getId(), $attr->getMinValue(), $attr->getMaxValue(), $attr->getValue(), $attr->getDefaultValue(), []);
}, $this->attributeMap->getAll()),
```

**Comment by dries-c** [comment]
This doesn't work since the UpdateAttribute has more fields
