### ISSUE TITLE
ItemTranslator Error

### ISSUE THREAD

**Issue by nzAily** [NetherGamesMC/PocketMine-MP#499]
[16:19:58.000] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: Username
[16:19:58.001] [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Unmapped blockstate returned by blockstate serializer: TAG_Compound={ "name" => TAG_String="minecraft:player_head" "version" => TAG_Int=18163713 "states" => TAG_Compound={ "facing_direction" => TAG_Int=2 } "PMMPDataVersion" => TAG_Long=1 }" (EXCEPTION) in "pmsrc/src/network/mcpe/convert/ItemTranslator" at line 93
--- Stack trace ---
  #0 pmsrc/src/network/mcpe/convert/ItemTranslator(61): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkId(object pocketmine\item\ItemBlock#337276)
  #1 pmsrc/src/network/mcpe/convert/TypeConverter(228): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkIdQuiet(object pocketmine\item\ItemBlock#337276)
  #2 pmsrc/src/network/mcpe/cache/CreativeInventoryCache(64): pocketmine\network\mcpe\convert\TypeConverter->coreItemStackToNet(object pocketmine\item\ItemBlock#337276)
  #3 pmsrc/src/network/mcpe/cache/CreativeInventoryCache(51): pocketmine\network\mcpe\cache\CreativeInventoryCache->buildCreativeInventoryCache(object pocketmine\inventory\CreativeInventory#53628)
  #4 pmsrc/src/network/mcpe/InventoryManager(696): pocketmine\network\mcpe\cache\CreativeInventoryCache->getCache(object pocketmine\inventory\CreativeInventory#53628)
  #5 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(146): pocketmine\network\mcpe\InventoryManager->syncCreative()
  #6 pmsrc/src/network/mcpe/NetworkSession(372): pocketmine\network\mcpe\handler\PreSpawnPacketHandler->setUp()
  #7 pmsrc/src/network/mcpe/NetworkSession(1008): pocketmine\network\mcpe\NetworkSession->setHandler(object pocketmine\network\mcpe\handler\PreSpawnPacketHandler#338072)
  #8 pmsrc/src/network/mcpe/NetworkSession(323): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
  #9 pmsrc/src/promise/Promise(47): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#338141)
  #10 pmsrc/src/network/mcpe/NetworkSession(258): pocketmine\promise\Promise->onCompletion(object Closure#160515, object Closure#160585)
  #11 pmsrc/src/network/mcpe/NetworkSession(1003): pocketmine\network\mcpe\NetworkSession->createPlayer()
  #12 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(187): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #13 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#338219)
  #14 pmsrc/src/network/mcpe/NetworkSession(531): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#338145)
  #15 pmsrc/src/network/mcpe/NetworkSession(469): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#338219, string[4] ....)
  #16 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[6] ......)
  #17 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[15] .'9S....n....-a)
  #18 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#324632)
  #19 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #21 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #22 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #23 pmsrc/src/Server(1743): pocketmine\snooze\SleeperHandler->sleepUntil(float 1729786797.8605)
  #24 pmsrc/src/Server(1110): pocketmine\Server->tickProcessor()
  #25 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
  #26 pmsrc/src/PocketMine(378): pocketmine\server()
  #27 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPvGAOyT.tar/src/PocketMine.php)
--- End of exception information ---

**Comment by dries-c** [comment]
Which version of minecraft are you using?

**Comment by nzAily** [comment]
> Which version of minecraft are you using?

1.21.31

**Comment by nzAily** [comment]
However, if you run it on Windows it runs normally and if you run it on Linux this problem appears

**Comment by dries-c** [comment]
That makes little sense though and i don't seem to be able to reproduce it, are you sure you got the latest changes?

**Comment by nzAily** [comment]
> That makes little sense though and i don't seem to be able to reproduce it, are you sure you got the latest changes?

Sorry, it turns out that when I tried again in Windows, the same error appeared.
![image](https://github.com/user-attachments/assets/f1a23ea1-80f3-4077-a60f-1e9a5bbbf0b6)

**Comment by dries-c** [comment]
I can't reproduce this error, are you sure you're running the latest version of bedrockdata, the item upgrader and the block upgrader?

**Comment by nzAily** [comment]
> I can't reproduce this error, are you sure you're running the latest version of bedrockdata, the item upgrader and the block upgrader?

Yes, I am sure I have used the latest version of the Bedrock data, item upgrader, and block upgrader
but when i join using the latest version of minecraft (1.21.41) it's fine

**Comment by dries-c** [comment]
[PocketMine-MP.phar.zip](https://github.com/user-attachments/files/17521610/PocketMine-MP.phar.zip)
Can you try this phar and let me know if it happens? Since I just can't reproduce it

**Comment by nzAily** [comment]
> [PocketMine-MP.phar.zip](https://github.com/user-attachments/files/17521610/PocketMine-MP.phar.zip) Can you try this phar and let me know if it happens? Since I just can't reproduce it

okay, i will try it

**Comment by nzAily** [comment]
> [PocketMine-MP.phar.zip](https://github.com/user-attachments/files/17521610/PocketMine-MP.phar.zip) Can you try this phar and let me know if it happens? Since I just can't reproduce it

![Untitled](https://github.com/user-attachments/assets/06ccc135-3e05-4680-91ae-ee88254ad1f1)
I've tried it but the problem still appears

**Comment by dries-c** [comment]
Did you try without plugins?

**Comment by nzAily** [comment]
> Did you try without plugins?

If you don't have plugins, you can, but the plugins I use require ItemTranslator and I've checked and discussed the plugins and there are no problems.

**Comment by dries-c** [comment]
Disable it and check if it still happens, if it doesn't it's a problem of the plugin

**Comment by nzAily** [comment]
> Disable it and check if it still happens, if it doesn't it's a problem of the plugin

okay it worked

**Comment by nzAily** [comment]
so can't i use "pocketmine\utils\AssumptionFailedError"?

https://github.com/DavyCraft648/Customies-NG/issues/13
